defaults: &defaults
  docker: [image: 'circleci/openjdk:8-jdk']
  working_directory: ~/repo
  environment:
    TERM: dumb
    JVM_OPTS: -Xmx1024m -Xms512m
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError"'

version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          context: org-global
          requires: [build]
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Sync submodules
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: Update external dependencies
          command: ./gradlew --stacktrace updateDependencies
      - run:
          name: Generate artifacts
          command: ./gradlew --stacktrace publish
      - store_artifacts:
          path: &out build/out
          destination: maven-repo
      - persist_to_workspace:
          root: .
          paths: [*out]
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Upload artifacts
          command: gradle --stacktrace upload
